require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

Naming/MethodParameterName:
  AllowedNames:
    - kw

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  EnforcedStyle: brackets
